XSD validation for Lucene datastore
apache/gora pull request #227
Opened 2020-10-23 21:35 UTC by mgov88

I implemented an XSD validation for the Lucene Datastore, I would like to know if I did it correctly, so I can go on and repeat this implementation for the other datastores.

I created this PR as a draft, when I finish the rest of datastores I will send a complete PR.

Issue: [GORA-455 Create XSD's for all datastore xml mapping files](https://issues.apache.org/jira/projects/GORA/issues/GORA-455)

2020-10-25 20:44 UTC, jhnmora000 requested changes
please address these comments before you start working on other datastores.

2020-10-25 20:44 UTC, jhnmora000 commented on gora-lucene/src/test/conf/gora-lucene.xsd
> +<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
please add the Apache 2.0 License notice for this file

2020-10-25 20:44 UTC, jhnmora000 commented on gora-lucene/src/test/conf/gora-lucene.xsd
> +    <xs:element name="gora-otd" type="lucene-mapping"/>
format this file with 2-space indentation

2020-10-25 20:44 UTC, jhnmora000 commented on gora-lucene/src/test/conf/gora-lucene.xsd
> +<?xml version="1.0" encoding="UTF-8" ?>
IMHO, a schema file should not be placed in the tests of the datastore

2020-10-26 22:05 UTC, mgov88 commented on gora-lucene/src/test/conf/gora-lucene.xsd
> +<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
Thanks for your feedback, I will add it

2020-10-26 22:07 UTC, mgov88 commented on gora-lucene/src/test/conf/gora-lucene.xsd
> +    <xs:element name="gora-otd" type="lucene-mapping"/>
Sorry , I did realised that I used the wrong indentation

2020-10-26 22:08 UTC, mgov88 commented on gora-lucene/src/test/conf/gora-lucene.xsd
> +<?xml version="1.0" encoding="UTF-8" ?>
I am going to move the schema file to a 'resources' folder in the main code of the module.

2020-10-26 23:53 UTC, alfonsonishikawa commented
Would be desirable to add the XSD reference to the Lucene mapping XMLs (for sure there is some XML mapping in tests).

2020-10-28 20:01 UTC, alfonsonishikawa commented on gora-lucene/src/test/conf/gora-lucene-mapping.xml
> +          xsi:noNamespaceSchemaLocation="gora-lucene.xsd">
What does "noNamespaceSchemaLocation" means? Is that the default namespace? Do <class> and <primarykey> use that by default?
I suggest to create a Unit Test to check that an ill-formed mapping does not pass the validation.

2020-10-28 20:42 UTC, mgov88 commented on gora-lucene/src/test/conf/gora-lucene-mapping.xml
> +          xsi:noNamespaceSchemaLocation="gora-lucene.xsd">
Hi, it found examples on the internet that used that attributes to link to local XSD files, I guess this noNamespaceSchemaLocation is used if there is not a Namespaces defined in the XML.

I will try to implement a test

2020-10-29 00:14 UTC, mgov88 commented on gora-lucene/src/test/conf/gora-lucene-mapping.xml
> +          xsi:noNamespaceSchemaLocation="gora-lucene.xsd">
I developed a test. When a bad XML file is parsed this exception triggers:

`org.apache.gora.util.GoraException: java.io.IOException: Unable to read gora-lucene-mapping-bad.xml
	at org.apache.gora.lucene.store.TestLuceneStore.testXSDValidation(TestLuceneStore.java:178)
Caused by: java.io.IOException: Unable to read gora-lucene-mapping-bad.xml
	at org.apache.gora.lucene.store.TestLuceneStore.testXSDValidation(TestLuceneStore.java:178)
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'Field'. One of '{primarykey}' is expected.
	at org.apache.gora.lucene.store.TestLuceneStore.testXSDValidation(TestLuceneStore.java:178)`

2020-10-29 22:34 UTC, alfonsonishikawa commented
Good to see it works! :)
The last thing I would ask for is to add an opt-out (or opt-in) option to gora.properties to enable/disable verification.

2020-10-31 00:47 UTC, merged

2020-10-31 00:47 UTC, alfonsonishikawa commented
Merged to master. Thank you, @mgov88 !